# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wwwla-1f5LpfhWkU3b_pSpl-tyO47DdE
"""

import pandas as pd
import matplotlib.pyplot as plt

# Örnek bir veri oluşturalım (Gerçek veri yerine, basitleştirilmiş bir örnek)
data = {
    'Kategori': ['Uçuş Arama Deneyimi', 'Uçuş Deneyimi', 'Diğer'],
    'Sentiment Score': [13, 17, 0]
}
df = pd.DataFrame(data)

# Kategorilere göre sentiment skorlarını görselleştirme
plt.figure(figsize=(10, 6))
df.set_index('Kategori')['Sentiment Score'].plot(kind='bar', color='skyblue')
plt.title('Kategorilere Göre Pulse Skoru')
plt.ylabel('Pulse Skoru')
plt.xlabel('Kategori')
plt.xticks(rotation=45)
plt.tight_layout()

# Grafiği gösterme
plt.show()
