# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ka5VkJhQgzfXShR1fOxAuQzFSfWtcgJj
"""

# Gerekli kütüphaneleri yükleme
!pip install requests beautifulsoup4 pandas openpyxl

# Kütüphaneleri içe aktarma
import requests
from bs4 import BeautifulSoup
import pandas as pd

# 1. Bilet.com'dan Ajet müşteri yorumlarını çekme
url = 'https://www.bilet.com/ucak-bileti/anadolujet/yorumlar'
response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')

# 2. Yorumların bulunduğu HTML class'ını bulma
yorumlar = soup.find_all('div', class_='comment mt10')  # Doğru class Bilet.com’dan alındı

# 3. Yorumları listeye ekleme
yorum_listesi = []
for yorum in yorumlar:
    yorum_text = yorum.get_text(strip=True)
    yorum_listesi.append(yorum_text)

# 4. DataFrame'e dönüştürme ve ilk 50 yorumu alma
df = pd.DataFrame(yorum_listesi, columns=['Yorum'])
df_50 = df.head(50)

# 5. Excel dosyasına kaydetme
df_50.to_excel('biletcom_50_yorum.xlsx', index=False)
print("Yorumlar başarıyla çekildi ve Excel dosyasına kaydedildi.")

# 6. Dosyayı bilgisayara indirmek için
files.download('biletcom_50_yorum.xlsx')